#!/usr/bin/perl
use v5.32;
use strict;
use warnings;

use IO::File;

my $debug = ($ENV{"CONFIGURATION"} || "Debug") ne "Release" ? "true" : "false";

my $git_branch_or_tag = `git symbolic-ref -q --short HEAD || git describe --tags --exact-match`;
my $git_commit = `git rev-parse HEAD`;
my $git_is_dirty = `git diff-index --quiet HEAD -- || echo dirty` =~ "dirty" ? "true" : "false";

my $build_date = `date -u +%Y-%m-%dT%H:%M:%SZ`;

chomp $git_branch_or_tag;
chomp $git_commit;
chomp $git_is_dirty;
chomp $build_date;

my $build_info = <<EOF;
// Auto-generated by genbuildinfo.pl

extension BuildInfo {
    static let current = BuildInfo(
        debug: $debug,
    
        gitBranch: "$git_branch_or_tag",
        gitCommitId: "$git_commit",
        gitIsDirty: $git_is_dirty,
        
        buildDate: "$build_date"
    )
}
EOF

my $build_info_file = new IO::File(">BuildInfo.swift");

$build_info_file->print($build_info);
$build_info_file->close;
